export const LANGUAGE_LABELS: Record<string, string> = {
  uk: 'Ukrainian',
  en: 'English',
  ru: 'Russian',
  es: 'Spanish',
}

export const COUNTRY_LABELS: Record<string, string> = {
  UA: 'Ukraine',
  US: 'United States',
  GB: 'United Kingdom',
  DE: 'Germany',
  ES: 'Spain',
  FR: 'France',
  PL: 'Poland',
  CA: 'Canada',
  AU: 'Australia',
  IT: 'Italy',
  BR: 'Brazil',
  MX: 'Mexico',
  JP: 'Japan',
  KR: 'South Korea',
  IN: 'India',
  TR: 'Turkey',
  NL: 'Netherlands',
  SE: 'Sweden',
  NO: 'Norway',
  DK: 'Denmark',
  FI: 'Finland',
  CZ: 'Czech Republic',
  AT: 'Austria',
  CH: 'Switzerland',
  PT: 'Portugal',
  RO: 'Romania',
  HU: 'Hungary',
  SK: 'Slovakia',
  BG: 'Bulgaria',
  HR: 'Croatia',
  RS: 'Serbia',
  GR: 'Greece',
  IE: 'Ireland',
  BE: 'Belgium',
  LT: 'Lithuania',
  LV: 'Latvia',
  EE: 'Estonia',
  IL: 'Israel',
  AE: 'UAE',
  SA: 'Saudi Arabia',
}
